### ISSUE TITLE
How to reduce heading and list spacing?

### ISSUE THREAD

**Issue by tungttnguyen** [ryanpeek/markdown_cv#2]
HI Ryan,

Thanks for sharing your template. I like it a lot!

However, I'd like to reduce the spacing between heading/section/subsection to make the CV more compact. I tried to modify the `.tex` template file 

	\titlespacing\section{-5pt}{0pt plus 0pt minus 0pt}{0pt plus 0pt minus 0pt}
	\titlespacing\subsection{-5pt}{0pt plus 0pt minus 0pt}{0pt plus 0pt minus 0pt}

The spacing didn't change that much

![big_spacing](https://user-images.githubusercontent.com/6590141/32288887-8a9c4ba2-bef2-11e7-890c-e34871311e01.png)

What I hope to get 

![small_spacing](https://user-images.githubusercontent.com/6590141/32288930-9dc0ba74-bef2-11e7-8b81-6706cb2cea2f.png)

Any suggestion? Thanks!

**Comment by ryanpeek** [comment]
I'm less savvy with modifying LaTex code, but have you tried adding \vspace{-2cm} inside of the title line? 

Something like: 

`\titlespacing\section{\vspace{-2cm}{0pt plus 0pt minus 0pt}{0pt plus 0pt minus 0pt}`

Or something along those lines. You May need to tweak that so it works (move the \vspace in or out of curly brackets for titlespacing or section). 
If you want a horizontal rule after each subsection you'd need to add `\hrule` in there as well.

Hope this helps.

**Comment by tungttnguyen** [comment]
Thanks @ryanpeek ! Looks like it's the only option. Let me try it out.
