### ISSUE TITLE
xelatex support

### ISSUE THREAD

**Issue by GuangchuangYu** [ryanpeek/markdown_cv#3]
I change the pdflatex engine to xelatex and it throw error when converting to pdf.

This is quite important for using Chinese fonts.

**Comment by GuangchuangYu** [comment]
after installing fontawesome, xelatex is working.

However, the default font seems to be different. any idea?

**Comment by ryanpeek** [comment]
Good to know it's working with xelatex. I'm less familiar with the inner workings, but perhaps see what the base fonts are for xelatex, and if you prefer the same as used by pdflatex, try downloading and changing with googlefonts? You can change the font settings using the fontfamily options. Currently I have the default set to `mathpazo` and fontfamilyoptions to `sc, osf`. Might be worth playing with those settings?
